#!/bin/bash
# Autor: Joonas Puur
# Skripti nimi: menu
# Ülesanne: kuvab söögimenüü ja väljastab vastava kirjelduse

echo "1) liha ja kartulid"
echo "2) kala ja krõpsud"
echo "3) supp ja salat"

read -p "Tee oma valik (1, 2 või 3): " valik

# Kontrollime, kas sisend on number 1–3
if ! [[ $valik =~ ^[1-3]$ ]]; then
    echo "VIGA: Palun vali ainult 1, 2 või 3!"
    exit 1
fi

case $valik in
    1)
        echo "Väga maitsev, aga jälgi oma tervist!"
        echo "Head isu!"
        ;;
    2)
        echo "Brititoit on maitsev!"
        echo "Head isu!"
        ;;
    3)
        echo "Nii tervislik ja igav..."
        echo "Head isu!"
        ;;
esac
